/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchEpisodeIdRouteImport } from './routes/watch.$episodeId'
import { Route as UUidRouteImport } from './routes/u.$uid'
import { Route as GenreGenreIdRouteImport } from './routes/genre.$genreId'
import { Route as ChatPeerIdRouteImport } from './routes/chat.$peerId'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime.$animeId'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchEpisodeIdRoute = WatchEpisodeIdRouteImport.update({
  id: '/watch/$episodeId',
  path: '/watch/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUidRoute = UUidRouteImport.update({
  id: '/u/$uid',
  path: '/u/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreGenreIdRoute = GenreGenreIdRouteImport.update({
  id: '/genre/$genreId',
  path: '/genre/$genreId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPeerIdRoute = ChatPeerIdRouteImport.update({
  id: '/chat/$peerId',
  path: '/chat/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/u/$uid': typeof UUidRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/search'
    | '/trending'
    | '/anime/$animeId'
    | '/chat/$peerId'
    | '/genre/$genreId'
    | '/u/$uid'
    | '/watch/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/search'
    | '/trending'
    | '/anime/$animeId'
    | '/chat/$peerId'
    | '/genre/$genreId'
    | '/u/$uid'
    | '/watch/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/search'
    | '/trending'
    | '/anime/$animeId'
    | '/chat/$peerId'
    | '/genre/$genreId'
    | '/u/$uid'
    | '/watch/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  SearchRoute: typeof SearchRoute
  TrendingRoute: typeof TrendingRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  ChatPeerIdRoute: typeof ChatPeerIdRoute
  GenreGenreIdRoute: typeof GenreGenreIdRoute
  UUidRoute: typeof UUidRoute
  WatchEpisodeIdRoute: typeof WatchEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$episodeId': {
      id: '/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof WatchEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$uid': {
      id: '/u/$uid'
      path: '/u/$uid'
      fullPath: '/u/$uid'
      preLoaderRoute: typeof UUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$genreId': {
      id: '/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId'
      preLoaderRoute: typeof GenreGenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$peerId': {
      id: '/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof ChatPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  SearchRoute: SearchRoute,
  TrendingRoute: TrendingRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  ChatPeerIdRoute: ChatPeerIdRoute,
  GenreGenreIdRoute: GenreGenreIdRoute,
  UUidRoute: UUidRoute,
  WatchEpisodeIdRoute: WatchEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
